name: blackbox_jaspr_example
description: Blackbox example for Jaspr with sync/async boxes.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.10.8 <4.0.0"

resolution: workspace

dependencies:
  blackbox: ^0.2.0
  blackbox_jaspr: ^0.0.1
  jaspr: ^0.22.3
  meta: ^1.17.0

dev_dependencies:
  jaspr_test: ^0.22.3
