part of blackbox_jaspr;

/// Rebuilds when any tracked box read during build changes.
///
/// Use this in the component tree and let `blackbox_codegen` wire tracking for
/// `@observable` boxes automatically.
///
/// Generated observable output getters call [ObservableOutputSource.reportRead]
/// from inside the generated box class. Application code should not call
/// tracking hooks manually.
mixin ObservableOutputSource<T> on OutputSource<T> {
  /// Reports a tracked read to the nearest active [BoxObserver].
  ///
  /// This hook exists for code generated by `blackbox_codegen` for
  /// `@observable` boxes. Do not call it manually from application code.
  @protected
  @nonVirtual
  void reportRead() => _BoxTracker._reportRead(this);
}

class BoxObserver extends StatefulComponent {
  /// Legacy bridge for already generated code.
  ///
  /// New code should not call this directly. Prefer `@observable` together
  /// with `blackbox_codegen`; newly generated boxes call
  /// [ObservableOutputSource.reportRead] instead.
  @Deprecated(
    'Legacy generated-code hook. Do not call manually. Use @observable with '
    'blackbox_codegen so generated output getters call reportRead().',
  )
  static void trackBox(OutputSource<dynamic> box) =>
      _BoxTracker._reportRead(box);

  const BoxObserver({super.key, required this.builder});

  final Component Function(BuildContext context) builder;

  @override
  State<BoxObserver> createState() => _BoxObserverState();
}

class _BoxObserverState extends State<BoxObserver> {
  late final _Reaction _reaction = _Reaction(_invalidate);

  void _invalidate() {
    if (!mounted) return;
    setState(() {});
  }

  @override
  Component build(BuildContext context) {
    _reaction.startTracking();
    try {
      return component.builder(context);
    } finally {
      _reaction.stopTracking();
    }
  }

  @override
  void dispose() {
    _reaction.dispose();
    super.dispose();
  }
}
