name: blackbox_workspace
environment:
  sdk: ">=3.10.8 <4.0.0"
dev_dependencies:
  melos: ^7.4.0
workspace:
  - packages/blackbox_core
  - packages/blackbox_support
  - packages/blackbox_flutter
  - packages/blackbox_jaspr
  - examples/blackbox_example
  - examples/blackbox_jaspr_example
melos:
  scripts:
    analyze:
      run: dart analyze .
      exec:
        concurrency: 1

    test:
      run: dart test
      exec:
        concurrency: 1

    clean:
      run: flutter clean || true
      exec:
        concurrency: 1
