name: blackbox_example
description: Blackbox example with sync/async boxes
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  blackbox: ^0.7.0

  blackbox_flutter: ^0.0.8

dev_dependencies:

flutter:
  uses-material-design: true
